import type { CamelotKey, Genre, Track } from "../types";
import { clamp, seededNoise } from "./math";

type TrackSpec = Omit<Track, "waveform"> & {
  shape?: "rolling" | "peak" | "deep" | "vocal" | "tool" | "switch";
};

function buildWaveform(track: TrackSpec): number[] {
  const points = 32;
  const shape = track.shape ?? "rolling";

  return Array.from({ length: points }, (_, index) => {
    const phase = index / (points - 1);
    const noise = (seededNoise(track.id, index) - 0.5) * 0.12;
    const introRamp = clamp(phase / 0.22);
    const outroDip = clamp((1 - phase) / 0.16);
    const dropPulse = Math.sin(phase * Math.PI * (track.dropCount + 1)) * 0.08;
    const breakdown =
      track.breakBars > 16
        ? -0.22 * Math.exp(-Math.pow((phase - 0.48) / 0.1, 2))
        : -0.1 * Math.exp(-Math.pow((phase - 0.52) / 0.14, 2));

    const shapeLift =
      shape === "peak"
        ? 0.18 * Math.sin(Math.PI * phase)
        : shape === "deep"
          ? -0.06 + 0.08 * Math.sin(Math.PI * phase)
          : shape === "vocal"
            ? 0.08 * Math.exp(-Math.pow((phase - 0.42) / 0.18, 2))
            : shape === "tool"
              ? -0.04
              : shape === "switch"
                ? 0.16 * Math.max(0, phase - 0.35)
                : 0.04 * Math.sin(Math.PI * phase);

    return clamp(track.energy * 0.68 + introRamp * 0.2 + outroDip * 0.08 + dropPulse + breakdown + shapeLift + noise);
  });
}

function track(spec: TrackSpec): Track {
  return {
    ...spec,
    waveform: buildWaveform(spec)
  };
}

const tracks: TrackSpec[] = [
  {
    id: "afterhours-residue",
    title: "Afterhours Residue",
    artist: "Luca Verdin",
    genre: "minimal deep house",
    bpm: 124,
    camelot: "8A",
    durationSec: 401,
    energy: 0.52,
    danceability: 0.84,
    popularity: 0.43,
    groove: 0.91,
    vocal: 0.08,
    bassWeight: 0.67,
    percussion: 0.74,
    brightness: 0.36,
    density: 0.44,
    introBars: 32,
    outroBars: 32,
    breakBars: 16,
    dropCount: 1,
    tags: ["warmup", "rolling bassline", "microhouse", "hypnotic"],
    soundcloudId: "100000001",
    shape: "deep"
  },
  {
    id: "terrace-lowlight",
    title: "Terrace Lowlight",
    artist: "Mara Sol",
    genre: "minimal deep house",
    bpm: 125,
    camelot: "8A",
    durationSec: 386,
    energy: 0.57,
    danceability: 0.88,
    popularity: 0.49,
    groove: 0.93,
    vocal: 0.14,
    bassWeight: 0.7,
    percussion: 0.76,
    brightness: 0.4,
    density: 0.5,
    introBars: 32,
    outroBars: 48,
    breakBars: 8,
    dropCount: 1,
    tags: ["minimal", "terrace", "subby", "vinyl"],
    soundcloudId: "100000002",
    shape: "rolling"
  },
  {
    id: "narrow-room",
    title: "Narrow Room",
    artist: "Sacha Arlen",
    genre: "minimal deep house",
    bpm: 123,
    camelot: "9A",
    durationSec: 372,
    energy: 0.49,
    danceability: 0.8,
    popularity: 0.35,
    groove: 0.89,
    vocal: 0.02,
    bassWeight: 0.62,
    percussion: 0.69,
    brightness: 0.31,
    density: 0.37,
    introBars: 48,
    outroBars: 48,
    breakBars: 24,
    dropCount: 1,
    tags: ["afterhours", "minimal", "deep", "spacious"],
    soundcloudId: "100000003",
    shape: "deep"
  },
  {
    id: "plastic-sunday",
    title: "Plastic Sunday",
    artist: "North Proxy",
    genre: "minimal deep house",
    bpm: 126,
    camelot: "9A",
    durationSec: 358,
    energy: 0.61,
    danceability: 0.9,
    popularity: 0.54,
    groove: 0.92,
    vocal: 0.12,
    bassWeight: 0.68,
    percussion: 0.82,
    brightness: 0.45,
    density: 0.55,
    introBars: 32,
    outroBars: 32,
    breakBars: 12,
    dropCount: 2,
    tags: ["romanian", "rolling", "club", "dry drums"],
    soundcloudId: "100000004",
    shape: "rolling"
  },
  {
    id: "pool-deck-static",
    title: "Pool Deck Static",
    artist: "Ivy Toma",
    genre: "minimal deep house",
    bpm: 125,
    camelot: "10A",
    durationSec: 390,
    energy: 0.55,
    danceability: 0.86,
    popularity: 0.47,
    groove: 0.88,
    vocal: 0.18,
    bassWeight: 0.59,
    percussion: 0.77,
    brightness: 0.43,
    density: 0.46,
    introBars: 32,
    outroBars: 48,
    breakBars: 16,
    dropCount: 1,
    tags: ["sunset", "groovy", "warm", "minimal"],
    soundcloudId: "100000005",
    shape: "deep"
  },
  {
    id: "knock-two-times",
    title: "Knock Two Times",
    artist: "Rami Kole",
    genre: "tech house",
    bpm: 127,
    camelot: "10A",
    durationSec: 333,
    energy: 0.73,
    danceability: 0.93,
    popularity: 0.63,
    groove: 0.87,
    vocal: 0.2,
    bassWeight: 0.77,
    percussion: 0.86,
    brightness: 0.53,
    density: 0.65,
    introBars: 24,
    outroBars: 32,
    breakBars: 8,
    dropCount: 2,
    tags: ["tech house", "club", "fast mix", "percussive"],
    soundcloudId: "100000006",
    shape: "rolling"
  },
  {
    id: "bottle-service-loop",
    title: "Bottle Service Loop",
    artist: "Decker Lane",
    genre: "tech house",
    bpm: 128,
    camelot: "10A",
    durationSec: 312,
    energy: 0.82,
    danceability: 0.95,
    popularity: 0.81,
    groove: 0.84,
    vocal: 0.44,
    bassWeight: 0.83,
    percussion: 0.9,
    brightness: 0.61,
    density: 0.74,
    introBars: 16,
    outroBars: 24,
    breakBars: 8,
    dropCount: 2,
    tags: ["frat party", "peak", "vocal hook", "fast mix"],
    soundcloudId: "100000007",
    shape: "peak"
  },
  {
    id: "hands-up-sublet",
    title: "Hands Up Sublet",
    artist: "Kiro Rae",
    genre: "tech house",
    bpm: 128,
    camelot: "11A",
    durationSec: 327,
    energy: 0.79,
    danceability: 0.94,
    popularity: 0.76,
    groove: 0.85,
    vocal: 0.38,
    bassWeight: 0.79,
    percussion: 0.88,
    brightness: 0.57,
    density: 0.7,
    introBars: 16,
    outroBars: 32,
    breakBars: 12,
    dropCount: 2,
    tags: ["party", "call and response", "tech house", "recognizable"],
    soundcloudId: "100000008",
    shape: "vocal"
  },
  {
    id: "warehouse-smirk",
    title: "Warehouse Smirk",
    artist: "Tessa Way",
    genre: "tech house",
    bpm: 127,
    camelot: "11A",
    durationSec: 338,
    energy: 0.69,
    danceability: 0.89,
    popularity: 0.58,
    groove: 0.86,
    vocal: 0.08,
    bassWeight: 0.81,
    percussion: 0.84,
    brightness: 0.48,
    density: 0.62,
    introBars: 32,
    outroBars: 32,
    breakBars: 8,
    dropCount: 2,
    tags: ["warehouse", "tool", "punchy", "low vocal"],
    soundcloudId: "100000009",
    shape: "tool"
  },
  {
    id: "upstairs-signal",
    title: "Upstairs Signal",
    artist: "Nilo Vale",
    genre: "tech house",
    bpm: 126,
    camelot: "12A",
    durationSec: 347,
    energy: 0.71,
    danceability: 0.9,
    popularity: 0.61,
    groove: 0.87,
    vocal: 0.22,
    bassWeight: 0.75,
    percussion: 0.82,
    brightness: 0.55,
    density: 0.64,
    introBars: 24,
    outroBars: 32,
    breakBars: 16,
    dropCount: 2,
    tags: ["tech house", "late peak", "syncopated", "fast mix"],
    soundcloudId: "100000010",
    shape: "rolling"
  },
  {
    id: "velvet-turnaround",
    title: "Velvet Turnaround",
    artist: "Ari Medo",
    genre: "deep house",
    bpm: 122,
    camelot: "7A",
    durationSec: 418,
    energy: 0.46,
    danceability: 0.78,
    popularity: 0.4,
    groove: 0.78,
    vocal: 0.31,
    bassWeight: 0.52,
    percussion: 0.58,
    brightness: 0.42,
    density: 0.39,
    introBars: 48,
    outroBars: 48,
    breakBars: 32,
    dropCount: 1,
    tags: ["deep", "warmup", "soulful", "long blend"],
    soundcloudId: "100000011",
    shape: "deep"
  },
  {
    id: "late-checkout",
    title: "Late Checkout",
    artist: "Mina Byte",
    genre: "deep house",
    bpm: 123,
    camelot: "8A",
    durationSec: 397,
    energy: 0.5,
    danceability: 0.83,
    popularity: 0.51,
    groove: 0.84,
    vocal: 0.24,
    bassWeight: 0.6,
    percussion: 0.64,
    brightness: 0.38,
    density: 0.43,
    introBars: 48,
    outroBars: 40,
    breakBars: 24,
    dropCount: 1,
    tags: ["deep", "sunset", "patient", "soulful"],
    soundcloudId: "100000012",
    shape: "deep"
  },
  {
    id: "mirrorball-tax",
    title: "Mirrorball Tax",
    artist: "The Pax Room",
    genre: "house",
    bpm: 124,
    camelot: "8B",
    durationSec: 351,
    energy: 0.66,
    danceability: 0.91,
    popularity: 0.74,
    groove: 0.83,
    vocal: 0.47,
    bassWeight: 0.66,
    percussion: 0.76,
    brightness: 0.69,
    density: 0.61,
    introBars: 24,
    outroBars: 32,
    breakBars: 16,
    dropCount: 2,
    tags: ["classic house", "party", "vocal", "familiar"],
    soundcloudId: "100000013",
    shape: "vocal"
  },
  {
    id: "neon-porch",
    title: "Neon Porch",
    artist: "Emil Vale",
    genre: "house",
    bpm: 125,
    camelot: "9B",
    durationSec: 344,
    energy: 0.68,
    danceability: 0.9,
    popularity: 0.66,
    groove: 0.82,
    vocal: 0.35,
    bassWeight: 0.69,
    percussion: 0.79,
    brightness: 0.65,
    density: 0.6,
    introBars: 24,
    outroBars: 32,
    breakBars: 16,
    dropCount: 2,
    tags: ["house", "uplifting", "vocal", "party"],
    soundcloudId: "100000014",
    shape: "vocal"
  },
  {
    id: "corner-booth",
    title: "Corner Booth",
    artist: "Lupe Marin",
    genre: "minimal deep house",
    bpm: 126,
    camelot: "10A",
    durationSec: 376,
    energy: 0.62,
    danceability: 0.88,
    popularity: 0.52,
    groove: 0.91,
    vocal: 0.12,
    bassWeight: 0.72,
    percussion: 0.79,
    brightness: 0.44,
    density: 0.53,
    introBars: 32,
    outroBars: 48,
    breakBars: 8,
    dropCount: 2,
    tags: ["minimal", "tool", "rolling", "afterhours"],
    soundcloudId: "100000015",
    shape: "tool"
  },
  {
    id: "selecta-espresso",
    title: "Selecta Espresso",
    artist: "Raya Flo",
    genre: "tech house",
    bpm: 129,
    camelot: "11A",
    durationSec: 314,
    energy: 0.86,
    danceability: 0.96,
    popularity: 0.83,
    groove: 0.86,
    vocal: 0.52,
    bassWeight: 0.85,
    percussion: 0.91,
    brightness: 0.62,
    density: 0.79,
    introBars: 16,
    outroBars: 24,
    breakBars: 8,
    dropCount: 2,
    tags: ["frat party", "peak", "latin percussion", "fast mix"],
    soundcloudId: "100000016",
    shape: "peak"
  },
  {
    id: "basement-lemon",
    title: "Basement Lemon",
    artist: "Oren Dash",
    genre: "tech house",
    bpm: 128,
    camelot: "12A",
    durationSec: 322,
    energy: 0.8,
    danceability: 0.94,
    popularity: 0.72,
    groove: 0.82,
    vocal: 0.18,
    bassWeight: 0.86,
    percussion: 0.88,
    brightness: 0.56,
    density: 0.74,
    introBars: 16,
    outroBars: 32,
    breakBars: 8,
    dropCount: 2,
    tags: ["tech house", "peak", "bassline", "club"],
    soundcloudId: "100000017",
    shape: "peak"
  },
  {
    id: "casa-minute",
    title: "Casa Minute",
    artist: "Jules Ren",
    genre: "minimal deep house",
    bpm: 127,
    camelot: "12A",
    durationSec: 364,
    energy: 0.65,
    danceability: 0.9,
    popularity: 0.57,
    groove: 0.92,
    vocal: 0.1,
    bassWeight: 0.76,
    percussion: 0.81,
    brightness: 0.47,
    density: 0.57,
    introBars: 32,
    outroBars: 40,
    breakBars: 12,
    dropCount: 2,
    tags: ["minimal", "latin", "rolling", "fast mix"],
    soundcloudId: "100000018",
    shape: "rolling"
  },
  {
    id: "red-cup-resonance",
    title: "Red Cup Resonance",
    artist: "Kade Mason",
    genre: "tech house",
    bpm: 130,
    camelot: "1A",
    durationSec: 303,
    energy: 0.9,
    danceability: 0.95,
    popularity: 0.88,
    groove: 0.8,
    vocal: 0.58,
    bassWeight: 0.88,
    percussion: 0.92,
    brightness: 0.7,
    density: 0.82,
    introBars: 16,
    outroBars: 24,
    breakBars: 4,
    dropCount: 3,
    tags: ["frat party", "peak", "chant", "fast mix"],
    soundcloudId: "100000019",
    shape: "peak"
  },
  {
    id: "third-floor-knock",
    title: "Third Floor Knock",
    artist: "Sam Hollis",
    genre: "tech house",
    bpm: 129,
    camelot: "1A",
    durationSec: 318,
    energy: 0.84,
    danceability: 0.94,
    popularity: 0.79,
    groove: 0.84,
    vocal: 0.3,
    bassWeight: 0.87,
    percussion: 0.9,
    brightness: 0.61,
    density: 0.77,
    introBars: 16,
    outroBars: 24,
    breakBars: 8,
    dropCount: 2,
    tags: ["party", "peak", "tech house", "drum tool"],
    soundcloudId: "100000020",
    shape: "peak"
  },
  {
    id: "off-campus-clock",
    title: "Off Campus Clock",
    artist: "Vera Knox",
    genre: "tech house",
    bpm: 128,
    camelot: "2A",
    durationSec: 326,
    energy: 0.78,
    danceability: 0.93,
    popularity: 0.7,
    groove: 0.83,
    vocal: 0.26,
    bassWeight: 0.81,
    percussion: 0.85,
    brightness: 0.58,
    density: 0.71,
    introBars: 24,
    outroBars: 32,
    breakBars: 8,
    dropCount: 2,
    tags: ["tech house", "fast mix", "party", "bassline"],
    soundcloudId: "100000021",
    shape: "rolling"
  },
  {
    id: "stairs-to-delta",
    title: "Stairs to Delta",
    artist: "Milo Ames",
    genre: "minimal deep house",
    bpm: 126,
    camelot: "2A",
    durationSec: 381,
    energy: 0.6,
    danceability: 0.87,
    popularity: 0.5,
    groove: 0.89,
    vocal: 0.06,
    bassWeight: 0.7,
    percussion: 0.76,
    brightness: 0.42,
    density: 0.49,
    introBars: 48,
    outroBars: 48,
    breakBars: 16,
    dropCount: 1,
    tags: ["minimal", "late night", "patient", "sub"],
    soundcloudId: "100000022",
    shape: "deep"
  },
  {
    id: "couch-mode",
    title: "Couch Mode",
    artist: "Ana Mire",
    genre: "deep house",
    bpm: 122,
    camelot: "6A",
    durationSec: 432,
    energy: 0.42,
    danceability: 0.76,
    popularity: 0.38,
    groove: 0.79,
    vocal: 0.22,
    bassWeight: 0.54,
    percussion: 0.56,
    brightness: 0.34,
    density: 0.34,
    introBars: 64,
    outroBars: 48,
    breakBars: 32,
    dropCount: 1,
    tags: ["warmup", "deep", "soulful", "low energy"],
    soundcloudId: "100000023",
    shape: "deep"
  },
  {
    id: "late-texture",
    title: "Late Texture",
    artist: "Nico Maren",
    genre: "minimal deep house",
    bpm: 124,
    camelot: "7A",
    durationSec: 405,
    energy: 0.48,
    danceability: 0.8,
    popularity: 0.41,
    groove: 0.86,
    vocal: 0.04,
    bassWeight: 0.58,
    percussion: 0.66,
    brightness: 0.35,
    density: 0.38,
    introBars: 48,
    outroBars: 64,
    breakBars: 24,
    dropCount: 1,
    tags: ["minimal", "warmup", "deep", "long blend"],
    soundcloudId: "100000024",
    shape: "deep"
  },
  {
    id: "liminal-bodega",
    title: "Liminal Bodega",
    artist: "Voss & Lira",
    genre: "minimal deep house",
    bpm: 125,
    camelot: "7A",
    durationSec: 388,
    energy: 0.53,
    danceability: 0.85,
    popularity: 0.46,
    groove: 0.9,
    vocal: 0.1,
    bassWeight: 0.65,
    percussion: 0.71,
    brightness: 0.39,
    density: 0.43,
    introBars: 48,
    outroBars: 48,
    breakBars: 16,
    dropCount: 1,
    tags: ["minimal", "deep", "warm", "vinyl"],
    soundcloudId: "100000025",
    shape: "deep"
  },
  {
    id: "rolling-credit",
    title: "Rolling Credit",
    artist: "Mateo Finn",
    genre: "tech house",
    bpm: 126,
    camelot: "8A",
    durationSec: 348,
    energy: 0.68,
    danceability: 0.91,
    popularity: 0.62,
    groove: 0.88,
    vocal: 0.16,
    bassWeight: 0.76,
    percussion: 0.83,
    brightness: 0.51,
    density: 0.61,
    introBars: 32,
    outroBars: 32,
    breakBars: 8,
    dropCount: 2,
    tags: ["tech house", "rolling", "club", "groovy"],
    soundcloudId: "100000026",
    shape: "rolling"
  },
  {
    id: "postgame-kick",
    title: "Postgame Kick",
    artist: "Rafi Noir",
    genre: "tech house",
    bpm: 129,
    camelot: "9A",
    durationSec: 316,
    energy: 0.83,
    danceability: 0.94,
    popularity: 0.82,
    groove: 0.82,
    vocal: 0.42,
    bassWeight: 0.86,
    percussion: 0.89,
    brightness: 0.64,
    density: 0.76,
    introBars: 16,
    outroBars: 24,
    breakBars: 8,
    dropCount: 3,
    tags: ["frat party", "peak", "hook", "fast mix"],
    soundcloudId: "100000027",
    shape: "peak"
  },
  {
    id: "shared-location",
    title: "Shared Location",
    artist: "Inez Shore",
    genre: "tech house",
    bpm: 127,
    camelot: "9A",
    durationSec: 329,
    energy: 0.74,
    danceability: 0.92,
    popularity: 0.68,
    groove: 0.86,
    vocal: 0.31,
    bassWeight: 0.78,
    percussion: 0.84,
    brightness: 0.56,
    density: 0.68,
    introBars: 24,
    outroBars: 32,
    breakBars: 12,
    dropCount: 2,
    tags: ["party", "tech house", "groove", "fast mix"],
    soundcloudId: "100000028",
    shape: "rolling"
  },
  {
    id: "low-ceiling",
    title: "Low Ceiling",
    artist: "Tamir Vale",
    genre: "minimal deep house",
    bpm: 124,
    camelot: "6A",
    durationSec: 402,
    energy: 0.47,
    danceability: 0.79,
    popularity: 0.37,
    groove: 0.85,
    vocal: 0.03,
    bassWeight: 0.61,
    percussion: 0.64,
    brightness: 0.32,
    density: 0.36,
    introBars: 64,
    outroBars: 48,
    breakBars: 24,
    dropCount: 1,
    tags: ["minimal", "warmup", "afterhours", "deep"],
    soundcloudId: "100000029",
    shape: "deep"
  },
  {
    id: "front-yard-filter",
    title: "Front Yard Filter",
    artist: "Demi Ross",
    genre: "tech house",
    bpm: 128,
    camelot: "8B",
    durationSec: 306,
    energy: 0.81,
    danceability: 0.95,
    popularity: 0.84,
    groove: 0.81,
    vocal: 0.55,
    bassWeight: 0.8,
    percussion: 0.88,
    brightness: 0.71,
    density: 0.73,
    introBars: 16,
    outroBars: 24,
    breakBars: 8,
    dropCount: 2,
    tags: ["frat party", "vocal", "peak", "familiar"],
    soundcloudId: "100000030",
    shape: "vocal"
  },
  {
    id: "wide-open-clap",
    title: "Wide Open Clap",
    artist: "Max Fader",
    genre: "house",
    bpm: 126,
    camelot: "9B",
    durationSec: 334,
    energy: 0.73,
    danceability: 0.91,
    popularity: 0.78,
    groove: 0.79,
    vocal: 0.5,
    bassWeight: 0.7,
    percussion: 0.82,
    brightness: 0.74,
    density: 0.67,
    introBars: 24,
    outroBars: 32,
    breakBars: 16,
    dropCount: 2,
    tags: ["house", "party", "piano", "vocal"],
    soundcloudId: "100000031",
    shape: "vocal"
  },
  {
    id: "brownstone-runner",
    title: "Brownstone Runner",
    artist: "Vale North",
    genre: "uk garage",
    bpm: 130,
    camelot: "10B",
    durationSec: 286,
    energy: 0.76,
    danceability: 0.88,
    popularity: 0.67,
    groove: 0.74,
    vocal: 0.32,
    bassWeight: 0.82,
    percussion: 0.92,
    brightness: 0.66,
    density: 0.7,
    introBars: 16,
    outroBars: 16,
    breakBars: 8,
    dropCount: 2,
    tags: ["garage", "genre switch", "party", "fast mix"],
    soundcloudId: "100000032",
    shape: "switch"
  },
  {
    id: "vodka-cran-step",
    title: "Vodka Cran Step",
    artist: "Bria March",
    genre: "bass house",
    bpm: 128,
    camelot: "11B",
    durationSec: 292,
    energy: 0.89,
    danceability: 0.92,
    popularity: 0.86,
    groove: 0.72,
    vocal: 0.36,
    bassWeight: 0.95,
    percussion: 0.88,
    brightness: 0.73,
    density: 0.84,
    introBars: 16,
    outroBars: 16,
    breakBars: 4,
    dropCount: 3,
    tags: ["bass house", "frat party", "peak", "genre switch"],
    soundcloudId: "100000033",
    shape: "switch"
  },
  {
    id: "outdoor-rig",
    title: "Outdoor Rig",
    artist: "Sol and Seven",
    genre: "afro house",
    bpm: 122,
    camelot: "5A",
    durationSec: 412,
    energy: 0.57,
    danceability: 0.82,
    popularity: 0.58,
    groove: 0.8,
    vocal: 0.28,
    bassWeight: 0.62,
    percussion: 0.81,
    brightness: 0.52,
    density: 0.5,
    introBars: 48,
    outroBars: 48,
    breakBars: 24,
    dropCount: 1,
    tags: ["afro", "sunset", "percussion", "warm"],
    soundcloudId: "100000034",
    shape: "deep"
  },
  {
    id: "copper-marimba",
    title: "Copper Marimba",
    artist: "Amari Nile",
    genre: "afro house",
    bpm: 123,
    camelot: "6A",
    durationSec: 399,
    energy: 0.62,
    danceability: 0.86,
    popularity: 0.64,
    groove: 0.82,
    vocal: 0.24,
    bassWeight: 0.65,
    percussion: 0.86,
    brightness: 0.57,
    density: 0.55,
    introBars: 48,
    outroBars: 48,
    breakBars: 16,
    dropCount: 2,
    tags: ["afro", "percussion", "sunset", "organic"],
    soundcloudId: "100000035",
    shape: "rolling"
  },
  {
    id: "blue-hour-signal",
    title: "Blue Hour Signal",
    artist: "Cala Venn",
    genre: "melodic house",
    bpm: 124,
    camelot: "7A",
    durationSec: 438,
    energy: 0.58,
    danceability: 0.78,
    popularity: 0.55,
    groove: 0.7,
    vocal: 0.18,
    bassWeight: 0.58,
    percussion: 0.6,
    brightness: 0.62,
    density: 0.52,
    introBars: 64,
    outroBars: 48,
    breakBars: 48,
    dropCount: 1,
    tags: ["melodic", "sunset", "long blend", "emotional"],
    soundcloudId: "100000036",
    shape: "deep"
  },
  {
    id: "glass-elevator",
    title: "Glass Elevator",
    artist: "Mira Dawn",
    genre: "melodic house",
    bpm: 125,
    camelot: "8A",
    durationSec: 427,
    energy: 0.64,
    danceability: 0.8,
    popularity: 0.61,
    groove: 0.72,
    vocal: 0.34,
    bassWeight: 0.6,
    percussion: 0.62,
    brightness: 0.68,
    density: 0.57,
    introBars: 48,
    outroBars: 48,
    breakBars: 40,
    dropCount: 2,
    tags: ["melodic", "vocal", "late peak", "emotional"],
    soundcloudId: "100000037",
    shape: "vocal"
  },
  {
    id: "low-sun-reset",
    title: "Low Sun Reset",
    artist: "Oko & Wren",
    genre: "progressive house",
    bpm: 124,
    camelot: "8B",
    durationSec: 455,
    energy: 0.6,
    danceability: 0.77,
    popularity: 0.59,
    groove: 0.68,
    vocal: 0.22,
    bassWeight: 0.57,
    percussion: 0.58,
    brightness: 0.66,
    density: 0.54,
    introBars: 64,
    outroBars: 64,
    breakBars: 48,
    dropCount: 2,
    tags: ["progressive", "long blend", "melodic", "journey"],
    soundcloudId: "100000038",
    shape: "deep"
  },
  {
    id: "signal-hill",
    title: "Signal Hill",
    artist: "Riven Coast",
    genre: "progressive house",
    bpm: 126,
    camelot: "9B",
    durationSec: 448,
    energy: 0.7,
    danceability: 0.82,
    popularity: 0.65,
    groove: 0.7,
    vocal: 0.18,
    bassWeight: 0.63,
    percussion: 0.67,
    brightness: 0.72,
    density: 0.64,
    introBars: 64,
    outroBars: 48,
    breakBars: 32,
    dropCount: 2,
    tags: ["progressive", "late peak", "melodic", "big room"],
    soundcloudId: "100000039",
    shape: "peak"
  },
  {
    id: "ketama-pocket",
    title: "Ketama Pocket",
    artist: "Juno Bex",
    genre: "minimal deep house",
    bpm: 126,
    camelot: "3A",
    durationSec: 382,
    energy: 0.63,
    danceability: 0.88,
    popularity: 0.5,
    groove: 0.9,
    vocal: 0.07,
    bassWeight: 0.74,
    percussion: 0.78,
    brightness: 0.41,
    density: 0.52,
    introBars: 48,
    outroBars: 48,
    breakBars: 16,
    dropCount: 1,
    tags: ["minimal", "rolling", "long blend", "club"],
    soundcloudId: "100000040",
    shape: "rolling"
  },
  {
    id: "sublet-mirage",
    title: "Sublet Mirage",
    artist: "Eli Fane",
    genre: "minimal deep house",
    bpm: 127,
    camelot: "4A",
    durationSec: 369,
    energy: 0.66,
    danceability: 0.9,
    popularity: 0.55,
    groove: 0.91,
    vocal: 0.12,
    bassWeight: 0.75,
    percussion: 0.82,
    brightness: 0.45,
    density: 0.58,
    introBars: 32,
    outroBars: 48,
    breakBars: 8,
    dropCount: 2,
    tags: ["minimal", "techy", "late night", "rolling"],
    soundcloudId: "100000041",
    shape: "rolling"
  },
  {
    id: "main-room-murmur",
    title: "Main Room Murmur",
    artist: "Paz Viera",
    genre: "tech house",
    bpm: 128,
    camelot: "4A",
    durationSec: 326,
    energy: 0.76,
    danceability: 0.92,
    popularity: 0.69,
    groove: 0.84,
    vocal: 0.18,
    bassWeight: 0.8,
    percussion: 0.86,
    brightness: 0.55,
    density: 0.69,
    introBars: 24,
    outroBars: 32,
    breakBars: 8,
    dropCount: 2,
    tags: ["tech house", "club", "fast mix", "tool"],
    soundcloudId: "100000042",
    shape: "tool"
  },
  {
    id: "quick-charge",
    title: "Quick Charge",
    artist: "Belen Roy",
    genre: "tech house",
    bpm: 130,
    camelot: "5A",
    durationSec: 304,
    energy: 0.88,
    danceability: 0.95,
    popularity: 0.84,
    groove: 0.8,
    vocal: 0.48,
    bassWeight: 0.87,
    percussion: 0.91,
    brightness: 0.68,
    density: 0.82,
    introBars: 16,
    outroBars: 16,
    breakBars: 4,
    dropCount: 3,
    tags: ["frat party", "peak", "fast mix", "vocal hook"],
    soundcloudId: "100000043",
    shape: "peak"
  },
  {
    id: "thread-count",
    title: "Thread Count",
    artist: "Oska & Rue",
    genre: "minimal deep house",
    bpm: 125,
    camelot: "5A",
    durationSec: 395,
    energy: 0.54,
    danceability: 0.83,
    popularity: 0.42,
    groove: 0.88,
    vocal: 0.05,
    bassWeight: 0.66,
    percussion: 0.7,
    brightness: 0.37,
    density: 0.42,
    introBars: 64,
    outroBars: 48,
    breakBars: 24,
    dropCount: 1,
    tags: ["minimal", "deep", "patient", "warmup"],
    soundcloudId: "100000044",
    shape: "deep"
  },
  {
    id: "kitchen-island",
    title: "Kitchen Island",
    artist: "Nova Trace",
    genre: "house",
    bpm: 125,
    camelot: "5B",
    durationSec: 342,
    energy: 0.7,
    danceability: 0.91,
    popularity: 0.77,
    groove: 0.8,
    vocal: 0.52,
    bassWeight: 0.68,
    percussion: 0.78,
    brightness: 0.75,
    density: 0.66,
    introBars: 24,
    outroBars: 32,
    breakBars: 16,
    dropCount: 2,
    tags: ["house", "frat party", "vocal", "familiar"],
    soundcloudId: "100000045",
    shape: "vocal"
  },
  {
    id: "baseline-etiquette",
    title: "Baseline Etiquette",
    artist: "Calder Room",
    genre: "tech house",
    bpm: 128,
    camelot: "6A",
    durationSec: 321,
    energy: 0.77,
    danceability: 0.93,
    popularity: 0.66,
    groove: 0.84,
    vocal: 0.14,
    bassWeight: 0.83,
    percussion: 0.87,
    brightness: 0.54,
    density: 0.7,
    introBars: 24,
    outroBars: 32,
    breakBars: 8,
    dropCount: 2,
    tags: ["tech house", "tool", "bassline", "club"],
    soundcloudId: "100000046",
    shape: "tool"
  },
  {
    id: "wristband-season",
    title: "Wristband Season",
    artist: "Nadia Fox",
    genre: "tech house",
    bpm: 129,
    camelot: "6A",
    durationSec: 311,
    energy: 0.85,
    danceability: 0.94,
    popularity: 0.82,
    groove: 0.82,
    vocal: 0.46,
    bassWeight: 0.86,
    percussion: 0.89,
    brightness: 0.65,
    density: 0.79,
    introBars: 16,
    outroBars: 24,
    breakBars: 8,
    dropCount: 3,
    tags: ["frat party", "peak", "vocal", "fast mix"],
    soundcloudId: "100000047",
    shape: "peak"
  },
  {
    id: "patio-function",
    title: "Patio Function",
    artist: "Timo Rey",
    genre: "minimal deep house",
    bpm: 126,
    camelot: "6A",
    durationSec: 375,
    energy: 0.59,
    danceability: 0.87,
    popularity: 0.5,
    groove: 0.91,
    vocal: 0.1,
    bassWeight: 0.69,
    percussion: 0.76,
    brightness: 0.43,
    density: 0.5,
    introBars: 48,
    outroBars: 48,
    breakBars: 16,
    dropCount: 1,
    tags: ["minimal", "groovy", "patio", "warm"],
    soundcloudId: "100000048",
    shape: "rolling"
  },
  {
    id: "card-reader",
    title: "Card Reader",
    artist: "Laz Osca",
    genre: "tech house",
    bpm: 127,
    camelot: "7A",
    durationSec: 330,
    energy: 0.72,
    danceability: 0.91,
    popularity: 0.6,
    groove: 0.86,
    vocal: 0.18,
    bassWeight: 0.78,
    percussion: 0.84,
    brightness: 0.52,
    density: 0.64,
    introBars: 32,
    outroBars: 32,
    breakBars: 8,
    dropCount: 2,
    tags: ["tech house", "rolling", "club", "fast mix"],
    soundcloudId: "100000049",
    shape: "rolling"
  },
  {
    id: "guest-list-lag",
    title: "Guest List Lag",
    artist: "Mira Knox",
    genre: "tech house",
    bpm: 128,
    camelot: "7A",
    durationSec: 319,
    energy: 0.8,
    danceability: 0.94,
    popularity: 0.78,
    groove: 0.83,
    vocal: 0.41,
    bassWeight: 0.84,
    percussion: 0.88,
    brightness: 0.63,
    density: 0.75,
    introBars: 16,
    outroBars: 24,
    breakBars: 8,
    dropCount: 2,
    tags: ["frat party", "peak", "vocal", "tech house"],
    soundcloudId: "100000050",
    shape: "vocal"
  },
  {
    id: "channel-nine",
    title: "Channel Nine",
    artist: "Ion Crewe",
    genre: "minimal deep house",
    bpm: 124,
    camelot: "8A",
    durationSec: 408,
    energy: 0.5,
    danceability: 0.82,
    popularity: 0.39,
    groove: 0.87,
    vocal: 0.03,
    bassWeight: 0.6,
    percussion: 0.65,
    brightness: 0.34,
    density: 0.39,
    introBars: 64,
    outroBars: 64,
    breakBars: 32,
    dropCount: 1,
    tags: ["minimal", "afterhours", "deep", "long blend"],
    soundcloudId: "100000051",
    shape: "deep"
  },
  {
    id: "detached-garage",
    title: "Detached Garage",
    artist: "Theo Brin",
    genre: "uk garage",
    bpm: 130,
    camelot: "8A",
    durationSec: 298,
    energy: 0.78,
    danceability: 0.88,
    popularity: 0.73,
    groove: 0.72,
    vocal: 0.4,
    bassWeight: 0.83,
    percussion: 0.93,
    brightness: 0.67,
    density: 0.74,
    introBars: 16,
    outroBars: 16,
    breakBars: 8,
    dropCount: 2,
    tags: ["garage", "frat party", "switch", "fast mix"],
    soundcloudId: "100000052",
    shape: "switch"
  },
  {
    id: "halo-return",
    title: "Halo Return",
    artist: "Arno Lite",
    genre: "trance",
    bpm: 132,
    camelot: "9B",
    durationSec: 392,
    energy: 0.86,
    danceability: 0.82,
    popularity: 0.74,
    groove: 0.62,
    vocal: 0.18,
    bassWeight: 0.74,
    percussion: 0.74,
    brightness: 0.82,
    density: 0.76,
    introBars: 32,
    outroBars: 32,
    breakBars: 32,
    dropCount: 2,
    tags: ["trance", "finale", "genre switch", "hands up"],
    soundcloudId: "100000053",
    shape: "peak"
  },
  {
    id: "silver-terrace",
    title: "Silver Terrace",
    artist: "Jade Miro",
    genre: "melodic house",
    bpm: 124,
    camelot: "9A",
    durationSec: 429,
    energy: 0.62,
    danceability: 0.79,
    popularity: 0.6,
    groove: 0.69,
    vocal: 0.28,
    bassWeight: 0.58,
    percussion: 0.61,
    brightness: 0.7,
    density: 0.56,
    introBars: 64,
    outroBars: 48,
    breakBars: 40,
    dropCount: 2,
    tags: ["melodic", "sunset", "vocal", "late peak"],
    soundcloudId: "100000054",
    shape: "vocal"
  },
  {
    id: "balcony-clockwise",
    title: "Balcony Clockwise",
    artist: "Roe Canyon",
    genre: "progressive house",
    bpm: 126,
    camelot: "10B",
    durationSec: 446,
    energy: 0.74,
    danceability: 0.82,
    popularity: 0.66,
    groove: 0.7,
    vocal: 0.2,
    bassWeight: 0.64,
    percussion: 0.68,
    brightness: 0.75,
    density: 0.68,
    introBars: 48,
    outroBars: 48,
    breakBars: 32,
    dropCount: 2,
    tags: ["progressive", "late peak", "big", "melodic"],
    soundcloudId: "100000055",
    shape: "peak"
  },
  {
    id: "header-space",
    title: "Header Space",
    artist: "Kali Ren",
    genre: "minimal deep house",
    bpm: 123,
    camelot: "11A",
    durationSec: 414,
    energy: 0.47,
    danceability: 0.79,
    popularity: 0.34,
    groove: 0.84,
    vocal: 0.02,
    bassWeight: 0.57,
    percussion: 0.61,
    brightness: 0.31,
    density: 0.35,
    introBars: 64,
    outroBars: 64,
    breakBars: 32,
    dropCount: 1,
    tags: ["minimal", "warmup", "deep", "patient"],
    soundcloudId: "100000056",
    shape: "deep"
  },
  {
    id: "one-more-lap",
    title: "One More Lap",
    artist: "Rina Seve",
    genre: "tech house",
    bpm: 128,
    camelot: "12B",
    durationSec: 315,
    energy: 0.83,
    danceability: 0.94,
    popularity: 0.8,
    groove: 0.82,
    vocal: 0.5,
    bassWeight: 0.84,
    percussion: 0.89,
    brightness: 0.66,
    density: 0.78,
    introBars: 16,
    outroBars: 24,
    breakBars: 8,
    dropCount: 2,
    tags: ["frat party", "peak", "vocal", "fast mix"],
    soundcloudId: "100000057",
    shape: "vocal"
  },
  {
    id: "folding-table",
    title: "Folding Table",
    artist: "Benji North",
    genre: "bass house",
    bpm: 128,
    camelot: "12A",
    durationSec: 284,
    energy: 0.91,
    danceability: 0.92,
    popularity: 0.87,
    groove: 0.71,
    vocal: 0.34,
    bassWeight: 0.96,
    percussion: 0.9,
    brightness: 0.74,
    density: 0.86,
    introBars: 16,
    outroBars: 16,
    breakBars: 4,
    dropCount: 3,
    tags: ["bass house", "frat party", "finale", "switch"],
    soundcloudId: "100000058",
    shape: "switch"
  },
  {
    id: "lobby-operator",
    title: "Lobby Operator",
    artist: "Ira Moss",
    genre: "deep house",
    bpm: 123,
    camelot: "9A",
    durationSec: 410,
    energy: 0.51,
    danceability: 0.82,
    popularity: 0.45,
    groove: 0.82,
    vocal: 0.26,
    bassWeight: 0.57,
    percussion: 0.62,
    brightness: 0.4,
    density: 0.42,
    introBars: 48,
    outroBars: 48,
    breakBars: 24,
    dropCount: 1,
    tags: ["deep", "warmup", "soulful", "long blend"],
    soundcloudId: "100000059",
    shape: "deep"
  },
  {
    id: "roof-access",
    title: "Roof Access",
    artist: "Nell Corte",
    genre: "tech house",
    bpm: 127,
    camelot: "8A",
    durationSec: 337,
    energy: 0.75,
    danceability: 0.92,
    popularity: 0.71,
    groove: 0.85,
    vocal: 0.33,
    bassWeight: 0.79,
    percussion: 0.85,
    brightness: 0.59,
    density: 0.69,
    introBars: 24,
    outroBars: 32,
    breakBars: 8,
    dropCount: 2,
    tags: ["frat party", "club", "fast mix", "tech house"],
    soundcloudId: "100000060",
    shape: "rolling"
  },
  {
    id: "shift-drink",
    title: "Shift Drink",
    artist: "Karo Jet",
    genre: "tech house",
    bpm: 129,
    camelot: "8A",
    durationSec: 307,
    energy: 0.87,
    danceability: 0.95,
    popularity: 0.85,
    groove: 0.81,
    vocal: 0.56,
    bassWeight: 0.86,
    percussion: 0.9,
    brightness: 0.68,
    density: 0.82,
    introBars: 16,
    outroBars: 24,
    breakBars: 4,
    dropCount: 3,
    tags: ["frat party", "peak", "chant", "fast mix"],
    soundcloudId: "100000061",
    shape: "peak"
  },
  {
    id: "good-neighbor",
    title: "Good Neighbor",
    artist: "Pia Roon",
    genre: "house",
    bpm: 124,
    camelot: "7B",
    durationSec: 356,
    energy: 0.64,
    danceability: 0.89,
    popularity: 0.7,
    groove: 0.82,
    vocal: 0.45,
    bassWeight: 0.64,
    percussion: 0.75,
    brightness: 0.71,
    density: 0.6,
    introBars: 32,
    outroBars: 32,
    breakBars: 16,
    dropCount: 2,
    tags: ["house", "warm", "vocal", "party"],
    soundcloudId: "100000062",
    shape: "vocal"
  },
  {
    id: "side-chain-smile",
    title: "Side Chain Smile",
    artist: "Fenn Ward",
    genre: "tech house",
    bpm: 126,
    camelot: "7B",
    durationSec: 329,
    energy: 0.7,
    danceability: 0.91,
    popularity: 0.64,
    groove: 0.84,
    vocal: 0.24,
    bassWeight: 0.75,
    percussion: 0.82,
    brightness: 0.58,
    density: 0.64,
    introBars: 24,
    outroBars: 32,
    breakBars: 12,
    dropCount: 2,
    tags: ["tech house", "groove", "party", "fast mix"],
    soundcloudId: "100000063",
    shape: "rolling"
  },
  {
    id: "club-room-receipt",
    title: "Club Room Receipt",
    artist: "Luca Verdin",
    genre: "minimal deep house",
    bpm: 125,
    camelot: "9A",
    durationSec: 389,
    energy: 0.58,
    danceability: 0.86,
    popularity: 0.48,
    groove: 0.91,
    vocal: 0.06,
    bassWeight: 0.68,
    percussion: 0.75,
    brightness: 0.4,
    density: 0.47,
    introBars: 48,
    outroBars: 48,
    breakBars: 16,
    dropCount: 1,
    tags: ["minimal", "rolling", "afterhours", "long blend"],
    soundcloudId: "100000064",
    shape: "deep"
  },
  {
    id: "call-the-cab",
    title: "Call the Cab",
    artist: "Rio Lanza",
    genre: "tech house",
    bpm: 130,
    camelot: "10A",
    durationSec: 300,
    energy: 0.89,
    danceability: 0.95,
    popularity: 0.86,
    groove: 0.8,
    vocal: 0.6,
    bassWeight: 0.88,
    percussion: 0.92,
    brightness: 0.69,
    density: 0.83,
    introBars: 16,
    outroBars: 16,
    breakBars: 4,
    dropCount: 3,
    tags: ["frat party", "peak", "vocal hook", "finale"],
    soundcloudId: "100000065",
    shape: "peak"
  },
  {
    id: "broom-closet-groove",
    title: "Broom Closet Groove",
    artist: "Dax Prieto",
    genre: "minimal deep house",
    bpm: 126,
    camelot: "10A",
    durationSec: 371,
    energy: 0.6,
    danceability: 0.89,
    popularity: 0.46,
    groove: 0.92,
    vocal: 0.05,
    bassWeight: 0.7,
    percussion: 0.78,
    brightness: 0.42,
    density: 0.5,
    introBars: 48,
    outroBars: 48,
    breakBars: 12,
    dropCount: 1,
    tags: ["minimal", "rolling", "tool", "afterhours"],
    soundcloudId: "100000066",
    shape: "tool"
  },
  {
    id: "campus-afterimage",
    title: "Campus Afterimage",
    artist: "Leona Hart",
    genre: "melodic house",
    bpm: 126,
    camelot: "11B",
    durationSec: 406,
    energy: 0.76,
    danceability: 0.82,
    popularity: 0.69,
    groove: 0.68,
    vocal: 0.36,
    bassWeight: 0.68,
    percussion: 0.72,
    brightness: 0.78,
    density: 0.72,
    introBars: 32,
    outroBars: 32,
    breakBars: 24,
    dropCount: 2,
    tags: ["melodic", "finale", "vocal", "hands up"],
    soundcloudId: "100000067",
    shape: "peak"
  },
  {
    id: "last-house-light",
    title: "Last House Light",
    artist: "Milo Ames",
    genre: "deep house",
    bpm: 122,
    camelot: "12A",
    durationSec: 421,
    energy: 0.49,
    danceability: 0.79,
    popularity: 0.43,
    groove: 0.81,
    vocal: 0.2,
    bassWeight: 0.56,
    percussion: 0.6,
    brightness: 0.37,
    density: 0.39,
    introBars: 48,
    outroBars: 64,
    breakBars: 32,
    dropCount: 1,
    tags: ["deep", "warmup", "long blend", "soulful"],
    soundcloudId: "100000068",
    shape: "deep"
  }
];

export const demoCatalog: Track[] = tracks.map(track);

export const genres: Genre[] = [
  "minimal deep house",
  "deep house",
  "tech house",
  "melodic house",
  "afro house",
  "progressive house",
  "house",
  "bass house",
  "uk garage",
  "trance"
];

export function catalogById(): Map<string, Track> {
  return new Map(demoCatalog.map((entry) => [entry.id, entry]));
}
